<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyVersion>1.0.0.15</AssemblyVersion>
    <NoWarn>CS8618</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="woodgroveapi.Tests" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="woodgroveapi.Tests\**\*.cs" />
    <Content Remove="woodgroveapi.Tests\**\*" />
    <EmbeddedResource Remove="woodgroveapi.Tests\**\*" />
    <None Remove="woodgroveapi.Tests\**\*" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Communication.Email" Version="1.1.0" />
    <PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="2.23.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.10" />
    <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="10.0.10" />
    <PackageReference Include="Microsoft.Extensions.Logging.AzureAppServices" Version="10.0.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\migration\Woodgrove.Migration\Woodgrove.Migration.csproj" />
  </ItemGroup>

</Project>
